### ISSUE TITLE
OSError: image file is truncated

### ISSUE THREAD

**Issue by denghu333** [huangyangyi/TeCH#20]
In the Step Finetune Dreambooth model, I always get this error, Anyone met the same problem?
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 187, in advance
    batch = next(data_fetcher)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 265, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 280, in _fetch_next_batch
    batch = next(iterator)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 569, in __next__
    return self.request_next_batch(self.loader_iters)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 581, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File "/root/miniconda3/lib/python3.8/site-packages/lightning_utilities/core/apply_func.py", line 64, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/autodl-tmp/TeCH/utils/ldm_utils/ldm/data/personalized.py", line 294, in __getitem__
    img = np.array(image).astype(np.uint8)
  File "/root/miniconda3/lib/python3.8/site-packages/PIL/Image.py", line 701, in __array_interface__
    new["data"] = self.tobytes()
  File "/root/miniconda3/lib/python3.8/site-packages/PIL/Image.py", line 758, in tobytes
    self.load()
  File "/root/miniconda3/lib/python3.8/site-packages/PIL/ImageFile.py", line 266, in load
    raise OSError(msg)
OSError: image file is truncated (65 bytes not processed)

**Comment by denghu333** [comment]
I fixed it use this:
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

**Comment by 12awei** [comment]
Where is this code added? I added/root/miniconde3/lib/python3.8/site packages/PIL/ImageFile.py but it doesn't work

**Comment by jhpark98** [comment]
at TeCH/utils/ldm_utils/ldm/data/personalized.py

from PIL import Image
                    ↓
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
