### ISSUE TITLE
Problem of some implicit download from prohibited sites.

### ISSUE THREAD

**Issue by C-256** [huangyangyi/TeCH#25]
Thank you for your contribution. When I'm running `run.sh`, there was something wrong when running step 1 
感谢你们对于本项目的付出。当我在运行`run.sh`的第一个步骤时
`python utils/body_utils/preprocess.py --in_path ${INPUT_FILE} --out_dir ${EXP_DIR}`
 It seems to be like a network problem when downloading something. However, after reading `utils/body_utils/preprpcessors.py`, I have not found any explicit downloads. 
出现了一个问题。这个问题似乎和网络连接有关。但是查阅源代码`utils/body_utils/preprpcessors.py`后我们发现代码中没有显式下载文件的操作。

The followings are the error info.
以下是报错信息：

```
+ python utils/body_utils/preprocess.py --in_path ./input/examples/first.jpg --out_dir ./output/first
Resume Normal Estimator from  ./data/body_data/ckpt/normal.ckpt 
SMPL-X estimate with  PIXIE 
Dataset Size: 1
  0%|                                                                | 0/1 [00:00<?, ?it/s]Downloading model to /home/ac/program/anaconda3/envs/swcenv/lib/python3.10/site-packages/mediapipe/modules/pose_landmark/pose_landmark_heavy.tflite
  0%|                                                                | 0/1 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/home/ac/program/anaconda3/envs/myenv/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/ac/program/anaconda3/envs/myenv/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ac/program/anaconda3/envs/myenv/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ac/program/anaconda3/envs/myenv/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ac/program/anaconda3/envs/myenv/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/home/ac/program/anaconda3/envs/myenv/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/ac/program/anaconda3/envs/myenv/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/home/ac/program/anaconda3/envs/myenv/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/home/ac/program/anaconda3/envs/myenv/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/home/ac/program/anaconda3/envs/myenv/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

Could you please offer us the link or file which should be downloaded here? I'd appreciate it if you reply in your earliest convenienve.
烦请您提供一下此处下载的这些文件或其链接，感谢您的及时回复，谢谢。

**Comment by huangyangyi** [comment]
Hi, the model file you mention here should be `pose_landmark_heavy.tflite` checkpoint from `mediapipe`, you can download it from [the CDN link](https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.4/) and put it to the corresponding directory.
