### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by SLAGworld** [huangyangyi/TeCH#33]
When I reach step 4, the script fails with a segmentation fault. The terminal outputs the following error message:
python -X faulthandler utils/body_utils/postprocess.py --dir $EXP_DIR/obj --name $SUBJECT_NAME

Fatal Python error: Segmentation fault
Current thread 0x00007feb5d36d240 (most recent call first):
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 415 in __call__
  File "/opt/conda/lib/python3.9/site-packages/pyrender/renderer.py", line 614 in _bind_and_draw_primitive
  File "/opt/conda/lib/python3.9/site-packages/pyrender/renderer.py", line 389 in _forward_pass
  File "/opt/conda/lib/python3.9/site-packages/pyrender/renderer.py", line 144 in render
  File "/opt/conda/lib/python3.9/site-packages/pyrender/offscreen.py", line 104 in render
  File "/data/TeCH/utils/body_utils/lib/common/render_pyrender.py", line 141 in get_image
  File "/data/TeCH/utils/body_utils/postprocess.py", line 118 in get_occ_map
  File "/data/TeCH/utils/body_utils/postprocess.py", line 125 in <module>
Segmentation fault (core dumped)

**Comment by SLAGworld** [comment]
After switching to EGL, I received more detailed error messages：
Traceback (most recent call last):
  File "/data/TeCH/utils/body_utils/postprocess.py", line 132, in <module>
    left_occ_map = get_occ_map(tech_obj_cp, tech_vert_seg, L_labels_remove, L_labels_occ, 2048)
  File "/data/TeCH/utils/body_utils/postprocess.py", line 125, in get_occ_map
    _, mask_remove = renderer.get_image('front')
  File "/data/TeCH/utils/body_utils/lib/common/render_pyrender.py", line 142, in get_image
    color, depth = self.renderer.render(
  File "/opt/conda/lib/python3.9/site-packages/pyrender/offscreen.py", line 102, in render
    retval = self._renderer.render(scene, flags, seg_node_map)
  File "/opt/conda/lib/python3.9/site-packages/pyrender/renderer.py", line 144, in render
    retval = self._forward_pass(scene, flags, seg_node_map=seg_node_map)
  File "/opt/conda/lib/python3.9/site-packages/pyrender/renderer.py", line 326, in _forward_pass
    self._configure_forward_pass_viewport(flags)
  File "/opt/conda/lib/python3.9/site-packages/pyrender/renderer.py", line 1012, in _configure_forward_pass_viewport
    self._configure_main_framebuffer()
  File "/opt/conda/lib/python3.9/site-packages/pyrender/renderer.py", line 1067, in _configure_main_framebuffer
    glRenderbufferStorage(
  File "/opt/conda/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1281,
        baseOperation = glRenderbufferStorage,
        cArguments = (
                GL_RENDERBUFFER,
                GL_RGBA,
                16384,
                16384,
        )
)

**Comment by NeuroLord** [comment]
Have you been able to get around this error? I'm getting a similar message:
scripts/run.sh: line 47: 13007 Segmentation fault      python cores/main_mc.py --config configs/tech_mc_geometry.yaml --exp_dir ${EXP_DIR} --sub_name ${SUBJECT_NAME}

**Comment by amerssun** [comment]
same error

**Comment by jhpark98** [comment]
https://github.com/huangyangyi/TeCH/issues/11#issuecomment-1821899865

Maybe this could be solution to your problem?
